# Generated by Django 5.1.4 on 2024-12-17 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Convidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmar', models.BooleanField(default=False)),
                ('acompanhante_1', models.CharField(blank=True, max_length=50)),
                ('acompanhante_2', models.CharField(blank=True, max_length=50)),
                ('acompanhante_3', models.CharField(blank=True, max_length=50)),
                ('convidado', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('presente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.presente')),
            ],
        ),
    ]
