# Generated by Django 5.1.4 on 2024-12-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_presente_convidado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convite',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='convite',
            name='refletion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='convite',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='convite',
            name='versicle',
            field=models.TextField(blank=True),
        ),
    ]
