# Generated by Django 5.1.4 on 2024-12-21 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_convite_body_alter_convite_refletion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convite',
            name='agradecimento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='convite',
            name='palavra_noiva',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='convite',
            name='palavra_noivo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='convidado',
            name='presente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.presente'),
        ),
    ]
