# Generated by Django 5.1.4 on 2024-12-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_convite_agradecimento_convite_palavra_noiva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='convite',
            name='noiva',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='convite',
            name='noivo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
