# Generated by Django 5.1.4 on 2024-12-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_imagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='noivos',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='pagina_confirm_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='pagina_confirm_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='pagina_confirm_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='pagina_inicial',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='pagina_login',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='pagina_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
