# Generated by Django 5.1.4 on 2024-12-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_imagens_noivos_alter_imagens_pagina_confirm_1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagens',
            new_name='Imagen',
        ),
    ]
